# please make sure both gpt_caption.py and video_caption.py are availabel

export API_KEY=...
export API_BASE=...
export DATASET=...
export SAVE_DIR=...

clear
python gpt_caption.py --api_key=$API_KEY \
            --api_base=$API_BASE \
            --dataset_path=$DATASET \
            --save_path=$SAVE_DIR 